version: "3.1"

services:
  node:
    image: node:19.9.0-alpine3.16
    container_name: node
    working_dir: /home/node
    user: node
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - "./:/home/node"
    command: tail -f /dev/null

  banco:
    image: mysql:5.7.41
    restart: always
    container_name: banco
    ports:
      - 6603:3306
    volumes:
      - "database_mysql5:/var/lib/mysql"
      - "./banco.sql:/scripts/banco.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: aws_front_back

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: always
    container_name: phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - banco

volumes:
  database_mysql5:
    external: true
